version: 2.0

jobs:

  "mint-18":
    docker:
      - image: linuxmintd/linuxmint-sylvia
    steps:
      - checkout
      - run:
          name: Build Xapps
          command: mkdir -p /dependencies && cd /dependencies && mint-build xapps -i
      - run:
          name: Build Xreader
          command: mint-build -i

workflows:
  version: 2
  build:
    jobs:
      - "mint-18"
