version: 2.0

jobs:

  "mint-18":
    docker:
      - image: linuxmintd/linuxmint-sylvia
    steps:
      - checkout
      - run:
          name: Build Xapps
          command: mkdir -p /dependencies && cd /dependencies && mint-build xapps -i
      - run:
          name: Build Xreader
          command: mint-build -i

      - run:
          name: Prepare Artifacts
          command: |
            mkdir /artifacts;
            mv /dependencies/*/*.deb /artifacts/;
            mv /root/project/*.deb /artifacts/;

      - store_artifacts:
          path: /artifacts

workflows:
  version: 2
  build:
    jobs:
      - "mint-18"
